name: mind_space
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.2
  flex_color_scheme: ^8.1.1
  dio: ^5.8.0+1
  device_info_plus: ^11.2.2
  package_info_plus: ^8.2.1
  uuid: ^4.4.2
  crypto: ^3.0.6
  cached_network_image: ^3.3.1
  audioplayers: ^6.1.2
  flutter_markdown: 0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/